version: '2.4'
services:
  alpha-deploy-zf:
    image: harbor.do.proxima-ai.com/alpha/alpha-deploy:1.3
    runtime: nvidia
    restart: always
    environment:
      - LANG=C.UTF-8
    ports:
      - "30085:22"
      - "30086:8086"
      - "30087:8087"
      - "30088:8088"
      - "30089:8089"
    security_opt:
      - seccomp:unconfined
    container_name: alpha-deploy-zf
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/alpha_cpp/cmake:/opt/alpha/cmake
      - /home:/opt/alpha/host
      - /data:/data
      - /fileser:/fileser
    network_mode:
      bridge
    shm_size: 48G
    mem_limit: 48G
